vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products (Dossier ou on envoyera notre image)
    #        upload_destination: '%kernel.project_dir%/public/images/products'
